# Generated by Django 4.0.2 on 2022-02-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_catering_c_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='c_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catering',
            name='c_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catering',
            name='c_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='catering',
            name='c_details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catering',
            name='c_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catering',
            name='c_p_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='catering',
            name='c_types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
