# Generated by Django 4.0.2 on 2022-02-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_catering_c_name_alter_catering_c_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('contact_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('contact_Name', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=100)),
                ('contact_order', models.CharField(blank=True, max_length=100)),
                ('contact_quantity', models.CharField(blank=True, max_length=100)),
                ('contact_date', models.DateTimeField(blank=True)),
                ('contact_address', models.CharField(blank=True, max_length=100)),
                ('contact_details', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
    ]
