# Generated by Django 4.0.2 on 2022-02-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food1',
            fields=[
                ('food1_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('Photo', models.FileField(upload_to='food_images')),
            ],
            options={
                'db_table': 'food1',
            },
        ),
    ]
