# Generated by Django 4.0.2 on 2022-02-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
