# Generated by Django 4.0.2 on 2022-02-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0007_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered')], default='Ordered', max_length=50),
        ),
    ]
